## Import libraries

In [1]:
import folium
import pandas as pd
import json
from numpy import median
from folium import Choropleth, Circle, Marker, Icon, Map
import ast

In [2]:
df = pd.read_csv('data/df_api.csv')

In [3]:
df.head()

,name,total_money_raised,offices_country_code,offices_state_code,offices_latitude,offices_longitude,offices_address_1,offices_address_2,offices_zip_code,vegan_rest,num_vegan_rest,preschool,num_preschool,starbucks,num_starbucks,airport,num_airport,clubs,num_clubs,weighted_punct
0,Netbiscuits,$27M,USA,NY,40.746754,-73.995323,7th Floor,275 Seventh Ave,10001,"[{'fsq_id': '5287e35711d2ab3ea77f7ebb', 'categ...",10,"[{'fsq_id': '4d370251e4b4a09380322936', 'categ...",3,"[{'fsq_id': '506c7556e4b03bdbe5afda50', 'categ...",8,"[{'fsq_id': '4fd2219fe4b03e7cee27e882', 'categ...",10,"[{'fsq_id': '60da36b2d61cae1ce8d45a04', 'categ...",10,824.98
1,Aviary,$19M,USA,NY,40.749376,-73.996435,243 West 30th Street,11th Floor,10001,"[{'fsq_id': '5f161e6f978e663e91ab7155', 'categ...",10,"[{'fsq_id': '4d370251e4b4a09380322936', 'categ...",2,"[{'fsq_id': '55a555fd498e1727ae82a345', 'categ...",10,"[{'fsq_id': '4adb6119f964a520a72621e3', 'categ...",10,"[{'fsq_id': '4cc0b629f82ebfb7b4af6f91', 'categ...",8,821.40
2,Gilt Groupe,$236M,USA,NY,40.747270,-73.980064,2 Park Ave Fl 4,NaN,10016-5602,"[{'fsq_id': '4b02f734f964a520814b22e3', 'categ...",10,"[{'fsq_id': '52712a6911d25f0e0dfa94cb', 'categ...",1,"[{'fsq_id': '4aa01922f964a520483e20e3', 'categ...",10,"[{'fsq_id': '4a5623d5f964a52081b41fe3', 'categ...",10,"[{'fsq_id': '741d73901e18012f487f54d8', 'categ...",4,732.10
3,99designs,$35M,USA,CA,37.795531,-122.400598,447 Battery St.,3rd Floor,94111,"[{'fsq_id': '4b391baef964a520605625e3', 'categ...",10,"[{'fsq_id': '558a380a498e13330910aef6', 'categ...",1,"[{'fsq_id': '6167c8968b400716f1d65e0b', 'categ...",7,"[{'fsq_id': '535ece06498e564c67f2f049', 'categ...",9,"[{'fsq_id': '4f32bd4d19836c91c7f53884', 'categ...",7,699.97
4,Minted,$52.7M,USA,CA,37.797435,-122.403175,747 Front Street,2nd Floor,94111,"[{'fsq_id': '4b391baef964a520605625e3', 'categ...",10,"[{'fsq_id': '5cc0a9cac0c0840025deceea', 'categ...",3,"[{'fsq_id': '49d0da91f964a520395b1fe3', 'categ...",3,"[{'fsq_id': 'eb55470d48024203bb09894b', 'categ...",3,"[{'fsq_id': '55ed1abb498e9e55d2e0edfc', 'categ...",9,607.15

In [4]:
df_subset = df[df['weighted_punct'] > 600]

In [5]:
df_subset['vegan_rest'] = df_subset['vegan_rest'].apply(ast.literal_eval)

C:\Users\Laura\AppData\Local\Temp\ipykernel_26508\3433824591.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['vegan_rest'] = df_subset['vegan_rest'].apply(ast.literal_eval)

In [6]:
df_subset

,name,total_money_raised,offices_country_code,offices_state_code,offices_latitude,offices_longitude,offices_address_1,offices_address_2,offices_zip_code,vegan_rest,num_vegan_rest,preschool,num_preschool,starbucks,num_starbucks,airport,num_airport,clubs,num_clubs,weighted_punct
0,Netbiscuits,$27M,USA,NY,40.746754,-73.995323,7th Floor,275 Seventh Ave,10001,"[{'fsq_id': '5287e35711d2ab3ea77f7ebb', 'categ...",10,"[{'fsq_id': '4d370251e4b4a09380322936', 'categ...",3,"[{'fsq_id': '506c7556e4b03bdbe5afda50', 'categ...",8,"[{'fsq_id': '4fd2219fe4b03e7cee27e882', 'categ...",10,"[{'fsq_id': '60da36b2d61cae1ce8d45a04', 'categ...",10,824.98
1,Aviary,$19M,USA,NY,40.749376,-73.996435,243 West 30th Street,11th Floor,10001,"[{'fsq_id': '5f161e6f978e663e91ab7155', 'categ...",10,"[{'fsq_id': '4d370251e4b4a09380322936', 'categ...",2,"[{'fsq_id': '55a555fd498e1727ae82a345', 'categ...",10,"[{'fsq_id': '4adb6119f964a520a72621e3', 'categ...",10,"[{'fsq_id': '4cc0b629f82ebfb7b4af6f91', 'categ...",8,821.40
2,Gilt Groupe,$236M,USA,NY,40.747270,-73.980064,2 Park Ave Fl 4,NaN,10016-5602,"[{'fsq_id': '4b02f734f964a520814b22e3', 'categ...",10,"[{'fsq_id': '52712a6911d25f0e0dfa94cb', 'categ...",1,"[{'fsq_id': '4aa01922f964a520483e20e3', 'categ...",10,"[{'fsq_id': '4a5623d5f964a52081b41fe3', 'categ...",10,"[{'fsq_id': '741d73901e18012f487f54d8', 'categ...",4,732.10
3,99designs,$35M,USA,CA,37.795531,-122.400598,447 Battery St.,3rd Floor,94111,"[{'fsq_id': '4b391baef964a520605625e3', 'categ...",10,"[{'fsq_id': '558a380a498e13330910aef6', 'categ...",1,"[{'fsq_id': '6167c8968b400716f1d65e0b', 'categ...",7,"[{'fsq_id': '535ece06498e564c67f2f049', 'categ...",9,"[{'fsq_id': '4f32bd4d19836c91c7f53884', 'categ...",7,699.97
4,Minted,$52.7M,USA,CA,37.797435,-122.403175,747 Front Street,2nd Floor,94111,"[{'fsq_id': '4b391baef964a520605625e3', 'categ...",10,"[{'fsq_id': '5cc0a9cac0c0840025deceea', 'categ...",3,"[{'fsq_id': '49d0da91f964a520395b1fe3', 'categ...",3,"[{'fsq_id': 'eb55470d48024203bb09894b', 'categ...",3,"[{'fsq_id': '55ed1abb498e9e55d2e0edfc', 'categ...",9,607.15

In [7]:
#ast.literal_eval(df_subset['vegan_rest'][1])[0]

In [8]:
type(df_subset['vegan_rest'][0])

list

In [9]:
def pre_explode(x):
    new_dict = {}
    for i in df_subset['vegan_rest'][0]:
        lat = i["geocodes"]["main"]["latitude"]
        lon = i["geocodes"]["main"]["longitude"]
        new_dict = {"lat":lat, "lon":lon}
    return new_dict

In [10]:
df_subset['vegan_rest_2'] = df_subset['vegan_rest'].apply(pre_explode)
df_subset

C:\Users\Laura\AppData\Local\Temp\ipykernel_26508\3247127576.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['vegan_rest_2'] = df_subset['vegan_rest'].apply(pre_explode)

,name,total_money_raised,offices_country_code,offices_state_code,offices_latitude,offices_longitude,offices_address_1,offices_address_2,offices_zip_code,vegan_rest,...,preschool,num_preschool,starbucks,num_starbucks,airport,num_airport,clubs,num_clubs,weighted_punct,vegan_rest_2
0,Netbiscuits,$27M,USA,NY,40.746754,-73.995323,7th Floor,275 Seventh Ave,10001,"[{'fsq_id': '5287e35711d2ab3ea77f7ebb', 'categ...",...,"[{'fsq_id': '4d370251e4b4a09380322936', 'categ...",3,"[{'fsq_id': '506c7556e4b03bdbe5afda50', 'categ...",8,"[{'fsq_id': '4fd2219fe4b03e7cee27e882', 'categ...",10,"[{'fsq_id': '60da36b2d61cae1ce8d45a04', 'categ...",10,824.98,"{'lat': 40.74262, 'lon': -73.996447}"
1,Aviary,$19M,USA,NY,40.749376,-73.996435,243 West 30th Street,11th Floor,10001,"[{'fsq_id': '5f161e6f978e663e91ab7155', 'categ...",...,"[{'fsq_id': '4d370251e4b4a09380322936', 'categ...",2,"[{'fsq_id': '55a555fd498e1727ae82a345', 'categ...",10,"[{'fsq_id': '4adb6119f964a520a72621e3', 'categ...",10,"[{'fsq_id': '4cc0b629f82ebfb7b4af6f91', 'categ...",8,821.40,"{'lat': 40.74262, 'lon': -73.996447}"
2,Gilt Groupe,$236M,USA,NY,40.747270,-73.980064,2 Park Ave Fl 4,NaN,10016-5602,"[{'fsq_id': '4b02f734f964a520814b22e3', 'categ...",...,"[{'fsq_id': '52712a6911d25f0e0dfa94cb', 'categ...",1,"[{'fsq_id': '4aa01922f964a520483e20e3', 'categ...",10,"[{'fsq_id': '4a5623d5f964a52081b41fe3', 'categ...",10,"[{'fsq_id': '741d73901e18012f487f54d8', 'categ...",4,732.10,"{'lat': 40.74262, 'lon': -73.996447}"
3,99designs,$35M,USA,CA,37.795531,-122.400598,447 Battery St.,3rd Floor,94111,"[{'fsq_id': '4b391baef964a520605625e3', 'categ...",...,"[{'fsq_id': '558a380a498e13330910aef6', 'categ...",1,"[{'fsq_id': '6167c8968b400716f1d65e0b', 'categ...",7,"[{'fsq_id': '535ece06498e564c67f2f049', 'categ...",9,"[{'fsq_id': '4f32bd4d19836c91c7f53884', 'categ...",7,699.97,"{'lat': 40.74262, 'lon': -73.996447}"
4,Minted,$52.7M,USA,CA,37.797435,-122.403175,747 Front Street,2nd Floor,94111,"[{'fsq_id': '4b391baef964a520605625e3', 'categ...",...,"[{'fsq_id': '5cc0a9cac0c0840025deceea', 'categ...",3,"[{'fsq_id': '49d0da91f964a520395b1fe3', 'categ...",3,"[{'fsq_id': 'eb55470d48024203bb09894b', 'categ...",3,"[{'fsq_id': '55ed1abb498e9e55d2e0edfc', 'categ...",9,607.15,"{'lat': 40.74262, 'lon': -73.996447}"

In [11]:
df_subset['vegan_rest_2'][0]

{'lat': 40.74262, 'lon': -73.996447}

In [12]:
df_subset = df_subset.explode('vegan_rest_2')
df_subset = df_subset.reset_index(drop=True)

In [13]:
df_subset

,name,total_money_raised,offices_country_code,offices_state_code,offices_latitude,offices_longitude,offices_address_1,offices_address_2,offices_zip_code,vegan_rest,...,preschool,num_preschool,starbucks,num_starbucks,airport,num_airport,clubs,num_clubs,weighted_punct,vegan_rest_2
0,Netbiscuits,$27M,USA,NY,40.746754,-73.995323,7th Floor,275 Seventh Ave,10001,"[{'fsq_id': '5287e35711d2ab3ea77f7ebb', 'categ...",...,"[{'fsq_id': '4d370251e4b4a09380322936', 'categ...",3,"[{'fsq_id': '506c7556e4b03bdbe5afda50', 'categ...",8,"[{'fsq_id': '4fd2219fe4b03e7cee27e882', 'categ...",10,"[{'fsq_id': '60da36b2d61cae1ce8d45a04', 'categ...",10,824.98,lat
1,Netbiscuits,$27M,USA,NY,40.746754,-73.995323,7th Floor,275 Seventh Ave,10001,"[{'fsq_id': '5287e35711d2ab3ea77f7ebb', 'categ...",...,"[{'fsq_id': '4d370251e4b4a09380322936', 'categ...",3,"[{'fsq_id': '506c7556e4b03bdbe5afda50', 'categ...",8,"[{'fsq_id': '4fd2219fe4b03e7cee27e882', 'categ...",10,"[{'fsq_id': '60da36b2d61cae1ce8d45a04', 'categ...",10,824.98,lon
2,Aviary,$19M,USA,NY,40.749376,-73.996435,243 West 30th Street,11th Floor,10001,"[{'fsq_id': '5f161e6f978e663e91ab7155', 'categ...",...,"[{'fsq_id': '4d370251e4b4a09380322936', 'categ...",2,"[{'fsq_id': '55a555fd498e1727ae82a345', 'categ...",10,"[{'fsq_id': '4adb6119f964a520a72621e3', 'categ...",10,"[{'fsq_id': '4cc0b629f82ebfb7b4af6f91', 'categ...",8,821.40,lat
3,Aviary,$19M,USA,NY,40.749376,-73.996435,243 West 30th Street,11th Floor,10001,"[{'fsq_id': '5f161e6f978e663e91ab7155', 'categ...",...,"[{'fsq_id': '4d370251e4b4a09380322936', 'categ...",2,"[{'fsq_id': '55a555fd498e1727ae82a345', 'categ...",10,"[{'fsq_id': '4adb6119f964a520a72621e3', 'categ...",10,"[{'fsq_id': '4cc0b629f82ebfb7b4af6f91', 'categ...",8,821.40,lon
4,Gilt Groupe,$236M,USA,NY,40.747270,-73.980064,2 Park Ave Fl 4,NaN,10016-5602,"[{'fsq_id': '4b02f734f964a520814b22e3', 'categ...",...,"[{'fsq_id': '52712a6911d25f0e0dfa94cb', 'categ...",1,"[{'fsq_id': '4aa01922f964a520483e20e3', 'categ...",10,"[{'fsq_id': '4a5623d5f964a52081b41fe3', 'categ...",10,"[{'fsq_id': '741d73901e18012f487f54d8', 'categ...",4,732.10,lat
5,Gilt Groupe,$236M,USA,NY,40.747270,-73.980064,2 Park Ave Fl 4,NaN,10016-5602,"[{'fsq_id': '4b02f734f964a520814b22e3', 'categ...",...,"[{'fsq_id': '52712a6911d25f0e0dfa94cb', 'categ...",1,"[{'fsq_id': '4aa01922f964a520483e20e3', 'categ...",10,"[{'fsq_id': '4a5623d5f964a52081b41fe3', 'categ...",10,"[{'fsq_id': '741d73901e18012f487f54d8', 'categ...",4,732.10,lon
6,99designs,$35M,USA,CA,37.795531,-122.400598,447 Battery St.,3rd Floor,94111,"[{'fsq_id': '4b391baef964a520605625e3', 'categ...",...,"[{'fsq_id': '558a380a498e13330910aef6', 'categ...",1,"[{'fsq_id': '6167c8968b400716f1d65e0b', 'categ...",7,"[{'fsq_id': '535ece06498e564c67f2f049', 'categ...",9,"[{'fsq_id': '4f32bd4d19836c91c7f53884', 'categ...",7,699.97,lat
7,99designs,$35M,USA,CA,37.795531,-122.400598,447 Battery St.,3rd Floor,94111,"[{'fsq_id': '4b391baef964a520605625e3', 'categ...",...,"[{'fsq_id': '558a380a498e13330910aef6', 'categ...",1,"[{'fsq_id': '6167c8968b400716f1d65e0b', 'categ...",7,"[{'fsq_id': '535ece06498e564c67f2f049', 'categ...",9,"[{'fsq_id': '4f32bd4d19836c91c7f53884', 'categ...",7,699.97,lon
8,Minted,$52.7M,USA,CA,37.797435,-122.403175,747 Front Street,2nd Floor,94111,"[{'fsq_id': '4b391baef964a520605625e3', 'categ...",...,"[{'fsq_id': '5cc0a9cac0c0840025deceea', 'categ...",3,"[{'fsq_id': '49d0da91f964a520395b1fe3', 'categ...",3,"[{'fsq_id': 'eb55470d48024203bb09894b', 'categ...",3,"[{'fsq_id': '55ed1abb498e9e55d2e0edfc', 'categ...",9,607.15,lat
9,Minted,$52.7M,USA,CA,37.797435,-122.403175,747 Front Street,2nd Floor,94111,"[{'fsq_id': '4b391baef964a520605625e3', 'categ...",...,"[{'fsq_id': '5cc0a9cac0c0840025deceea', 'categ...",3,"[{'fsq_id': '49d0da91f964a520395b1fe3', 'categ...",3,"[{'fsq_id': 'eb55470d48024203bb09894b', 'categ...",3,"[{'fsq_id': '55ed1abb498e9e55d2e0edfc', 'categ...",9,607.15,lon

In [14]:
df_subset

,name,total_money_raised,offices_country_code,offices_state_code,offices_latitude,offices_longitude,offices_address_1,offices_address_2,offices_zip_code,vegan_rest,...,preschool,num_preschool,starbucks,num_starbucks,airport,num_airport,clubs,num_clubs,weighted_punct,vegan_rest_2
0,Netbiscuits,$27M,USA,NY,40.746754,-73.995323,7th Floor,275 Seventh Ave,10001,"[{'fsq_id': '5287e35711d2ab3ea77f7ebb', 'categ...",...,"[{'fsq_id': '4d370251e4b4a09380322936', 'categ...",3,"[{'fsq_id': '506c7556e4b03bdbe5afda50', 'categ...",8,"[{'fsq_id': '4fd2219fe4b03e7cee27e882', 'categ...",10,"[{'fsq_id': '60da36b2d61cae1ce8d45a04', 'categ...",10,824.98,lat
1,Netbiscuits,$27M,USA,NY,40.746754,-73.995323,7th Floor,275 Seventh Ave,10001,"[{'fsq_id': '5287e35711d2ab3ea77f7ebb', 'categ...",...,"[{'fsq_id': '4d370251e4b4a09380322936', 'categ...",3,"[{'fsq_id': '506c7556e4b03bdbe5afda50', 'categ...",8,"[{'fsq_id': '4fd2219fe4b03e7cee27e882', 'categ...",10,"[{'fsq_id': '60da36b2d61cae1ce8d45a04', 'categ...",10,824.98,lon
2,Aviary,$19M,USA,NY,40.749376,-73.996435,243 West 30th Street,11th Floor,10001,"[{'fsq_id': '5f161e6f978e663e91ab7155', 'categ...",...,"[{'fsq_id': '4d370251e4b4a09380322936', 'categ...",2,"[{'fsq_id': '55a555fd498e1727ae82a345', 'categ...",10,"[{'fsq_id': '4adb6119f964a520a72621e3', 'categ...",10,"[{'fsq_id': '4cc0b629f82ebfb7b4af6f91', 'categ...",8,821.40,lat
3,Aviary,$19M,USA,NY,40.749376,-73.996435,243 West 30th Street,11th Floor,10001,"[{'fsq_id': '5f161e6f978e663e91ab7155', 'categ...",...,"[{'fsq_id': '4d370251e4b4a09380322936', 'categ...",2,"[{'fsq_id': '55a555fd498e1727ae82a345', 'categ...",10,"[{'fsq_id': '4adb6119f964a520a72621e3', 'categ...",10,"[{'fsq_id': '4cc0b629f82ebfb7b4af6f91', 'categ...",8,821.40,lon
4,Gilt Groupe,$236M,USA,NY,40.747270,-73.980064,2 Park Ave Fl 4,NaN,10016-5602,"[{'fsq_id': '4b02f734f964a520814b22e3', 'categ...",...,"[{'fsq_id': '52712a6911d25f0e0dfa94cb', 'categ...",1,"[{'fsq_id': '4aa01922f964a520483e20e3', 'categ...",10,"[{'fsq_id': '4a5623d5f964a52081b41fe3', 'categ...",10,"[{'fsq_id': '741d73901e18012f487f54d8', 'categ...",4,732.10,lat
5,Gilt Groupe,$236M,USA,NY,40.747270,-73.980064,2 Park Ave Fl 4,NaN,10016-5602,"[{'fsq_id': '4b02f734f964a520814b22e3', 'categ...",...,"[{'fsq_id': '52712a6911d25f0e0dfa94cb', 'categ...",1,"[{'fsq_id': '4aa01922f964a520483e20e3', 'categ...",10,"[{'fsq_id': '4a5623d5f964a52081b41fe3', 'categ...",10,"[{'fsq_id': '741d73901e18012f487f54d8', 'categ...",4,732.10,lon
6,99designs,$35M,USA,CA,37.795531,-122.400598,447 Battery St.,3rd Floor,94111,"[{'fsq_id': '4b391baef964a520605625e3', 'categ...",...,"[{'fsq_id': '558a380a498e13330910aef6', 'categ...",1,"[{'fsq_id': '6167c8968b400716f1d65e0b', 'categ...",7,"[{'fsq_id': '535ece06498e564c67f2f049', 'categ...",9,"[{'fsq_id': '4f32bd4d19836c91c7f53884', 'categ...",7,699.97,lat
7,99designs,$35M,USA,CA,37.795531,-122.400598,447 Battery St.,3rd Floor,94111,"[{'fsq_id': '4b391baef964a520605625e3', 'categ...",...,"[{'fsq_id': '558a380a498e13330910aef6', 'categ...",1,"[{'fsq_id': '6167c8968b400716f1d65e0b', 'categ...",7,"[{'fsq_id': '535ece06498e564c67f2f049', 'categ...",9,"[{'fsq_id': '4f32bd4d19836c91c7f53884', 'categ...",7,699.97,lon
8,Minted,$52.7M,USA,CA,37.797435,-122.403175,747 Front Street,2nd Floor,94111,"[{'fsq_id': '4b391baef964a520605625e3', 'categ...",...,"[{'fsq_id': '5cc0a9cac0c0840025deceea', 'categ...",3,"[{'fsq_id': '49d0da91f964a520395b1fe3', 'categ...",3,"[{'fsq_id': 'eb55470d48024203bb09894b', 'categ...",3,"[{'fsq_id': '55ed1abb498e9e55d2e0edfc', 'categ...",9,607.15,lat
9,Minted,$52.7M,USA,CA,37.797435,-122.403175,747 Front Street,2nd Floor,94111,"[{'fsq_id': '4b391baef964a520605625e3', 'categ...",...,"[{'fsq_id': '5cc0a9cac0c0840025deceea', 'categ...",3,"[{'fsq_id': '49d0da91f964a520395b1fe3', 'categ...",3,"[{'fsq_id': 'eb55470d48024203bb09894b', 'categ...",3,"[{'fsq_id': '55ed1abb498e9e55d2e0edfc', 'categ...",9,607.15,lon

In [15]:
df_subset['vegan_rest_2'][0]

'lat'

In [16]:
ast.literal_eval(df_subset['vegan_rest'][3])

ValueError: malformed node or string: [{'fsq_id': '5f161e6f978e663e91ab7155', 'categories': [{'id': 13003, 'name': 'Bar', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/pub_', 'suffix': '.png'}}, {'id': 13303, 'name': 'Mexican Restaurant', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/mexican_', 'suffix': '.png'}}], 'chains': [], 'distance': 433, 'geocodes': {'main': {'latitude': 40.752566, 'longitude': -73.999722}, 'roof': {'latitude': 40.752566, 'longitude': -73.999722}}, 'link': '/v3/places/5f161e6f978e663e91ab7155', 'location': {'address': '450 W 33rd St', 'census_block': '360610103001003', 'country': 'US', 'cross_street': '', 'dma': 'New York', 'formatted_address': '450 W 33rd St, New York, NY 10001', 'locality': 'New York', 'postcode': '10001', 'region': 'NY'}, 'name': 'Jajaja Plantas Mexicana', 'related_places': {'parent': {'fsq_id': '5f0f9256e0ccd447d4424216', 'name': 'Whole Foods'}}, 'timezone': 'America/New_York'}, {'fsq_id': '4a639f9ff964a52077c51fe3', 'categories': [{'id': 13064, 'name': 'Pizzeria', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/pizza_', 'suffix': '.png'}}], 'chains': [], 'distance': 147, 'geocodes': {'drop_off': {'latitude': 40.750094, 'longitude': -73.995135}, 'main': {'latitude': 40.750153, 'longitude': -73.995215}, 'roof': {'latitude': 40.750153, 'longitude': -73.995215}}, 'link': '/v3/places/4a639f9ff964a52077c51fe3', 'location': {'address': '413 8th Ave', 'address_extended': 'btwn W 30th  W 31st St', 'census_block': '360610103001012', 'country': 'US', 'cross_street': 'btwn W 30th & W 31st St', 'dma': 'New York', 'formatted_address': '413 8th Ave (btwn W 30th & W 31st St), New York, NY 10001', 'locality': 'New York', 'postcode': '10001', 'region': 'NY'}, 'name': 'NY Pizza Suprema', 'related_places': {'children': []}, 'timezone': 'America/New_York'}, {'fsq_id': '49c406a8f964a5208d561fe3', 'categories': [{'id': 13001, 'name': 'Bagel Shop', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/bagels_', 'suffix': '.png'}}, {'id': 13068, 'name': 'American Restaurant', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/default_', 'suffix': '.png'}}, {'id': 13039, 'name': 'Deli', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/deli_', 'suffix': '.png'}}], 'chains': [], 'distance': 377, 'geocodes': {'main': {'latitude': 40.746151, 'longitude': -73.997547}, 'roof': {'latitude': 40.746151, 'longitude': -73.997547}}, 'link': '/v3/places/49c406a8f964a5208d561fe3', 'location': {'address': '286 8th Ave', 'address_extended': 'Frnt 1', 'census_block': '360610091001000', 'country': 'US', 'cross_street': 'btwn W 24th & W 25th St', 'dma': 'New York', 'formatted_address': '286 8th Ave (btwn W 24th & W 25th St), New York, NY 10001', 'locality': 'New York', 'postcode': '10001', 'region': 'NY'}, 'name': 'Brooklyn Bagel & Coffee Company', 'related_places': {}, 'timezone': 'America/New_York'}, {'fsq_id': '59ca57dd3d47910ad148e668', 'categories': [{'id': 13032, 'name': 'Cafes, Coffee, and Tea Houses', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/default_', 'suffix': '.png'}}], 'chains': [], 'distance': 361, 'geocodes': {'main': {'latitude': 40.752209, 'longitude': -73.998965}, 'roof': {'latitude': 40.752209, 'longitude': -73.998965}}, 'link': '/v3/places/59ca57dd3d47910ad148e668', 'location': {'address': '435 W 31st St', 'census_block': '360610103001009', 'country': 'US', 'cross_street': 'btwn 9th & Dyer Ave', 'dma': 'New York', 'formatted_address': '435 W 31st St (btwn 9th & Dyer Ave), New York, NY 10001', 'locality': 'New York', 'postcode': '10001', 'region': 'NY'}, 'name': 'Bluestone Lane Manhattan West Café', 'related_places': {'parent': {'fsq_id': '58c46579110d0304a1ae28ba', 'name': 'The Eugene Apartments'}}, 'timezone': 'America/New_York'}, {'fsq_id': '4f61235ce4b0d7325f17c638', 'categories': [{'id': 13002, 'name': 'Bakery', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/bakery_', 'suffix': '.png'}}, {'id': 13068, 'name': 'American Restaurant', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/default_', 'suffix': '.png'}}], 'chains': [], 'distance': 416, 'geocodes': {'main': {'latitude': 40.747313, 'longitude': -74.000432}, 'roof': {'latitude': 40.747313, 'longitude': -74.000432}}, 'link': '/v3/places/4f61235ce4b0d7325f17c638', 'location': {'address': '236 9th Ave', 'census_block': '360610093001001', 'country': 'US', 'cross_street': 'at 24th St', 'dma': 'New York', 'formatted_address': '236 9th Ave (at 24th St), New York, NY 10001', 'locality': 'New York', 'postcode': '10001', 'region': 'NY'}, 'name': 'Sullivan Street Bakery', 'related_places': {'children': []}, 'timezone': 'America/New_York'}, {'fsq_id': '6195afec8a1d954d76c8e668', 'categories': [{'id': 13009, 'name': 'Cocktail Bar', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/cocktails_', 'suffix': '.png'}}, {'id': 13302, 'name': 'Mediterranean Restaurant', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/mediterranean_', 'suffix': '.png'}}], 'chains': [], 'distance': 428, 'geocodes': {'main': {'latitude': 40.752873, 'longitude': -73.99838}, 'roof': {'latitude': 40.752873, 'longitude': -73.99838}}, 'link': '/v3/places/6195afec8a1d954d76c8e668', 'location': {'address': '385 9th Ave', 'address_extended': 'Ste 85', 'census_block': '360610103001008', 'country': 'US', 'cross_street': '31st St', 'dma': 'New York', 'formatted_address': '385 9th Ave (31st St), New York, NY 10001', 'locality': 'New York', 'postcode': '10001', 'region': 'NY'}, 'name': "Zou Zou's", 'related_places': {'parent': {'fsq_id': '613cf4bf07e7540226d7125a', 'name': 'Pendry'}, 'children': []}, 'timezone': 'America/New_York'}, {'fsq_id': '58d3f1e7528930281485076b', 'categories': [{'id': 13035, 'name': 'Coffee Shop', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/coffeeshop_', 'suffix': '.png'}}, {'id': 13065, 'name': 'Restaurant', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/default_', 'suffix': '.png'}}], 'chains': [], 'distance': 486, 'geocodes': {'drop_off': {'latitude': 40.745314, 'longitude': -73.994759}, 'main': {'latitude': 40.745153, 'longitude': -73.994538}, 'roof': {'latitude': 40.745153, 'longitude': -73.994538}}, 'link': '/v3/places/58d3f1e7528930281485076b', 'location': {'address': '261 7th Ave', 'census_block': '360610091005001', 'country': 'US', 'cross_street': 'at W 25th St', 'dma': 'New York', 'formatted_address': '261 7th Ave (at W 25th St), New York, NY 10001', 'locality': 'New York', 'postcode': '10001', 'region': 'NY'}, 'name': 'Variety Coffee Roasters', 'related_places': {}, 'timezone': 'America/New_York'}, {'fsq_id': '580e02c538fac6ce83d3b8c9', 'categories': [{'id': 13034, 'name': 'Café', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/cafe_', 'suffix': '.png'}}, {'id': 13035, 'name': 'Coffee Shop', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/coffeeshop_', 'suffix': '.png'}}, {'id': 13073, 'name': 'Australian Restaurant', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/australian_', 'suffix': '.png'}}], 'chains': [], 'distance': 375, 'geocodes': {'drop_off': {'latitude': 40.747864, 'longitude': -74.000635}, 'main': {'latitude': 40.748065, 'longitude': -74.000549}, 'roof': {'latitude': 40.748065, 'longitude': -74.000549}}, 'link': '/v3/places/580e02c538fac6ce83d3b8c9', 'location': {'address': '401 W 25th St', 'census_block': '360610093006000', 'country': 'US', 'cross_street': '9th Ave', 'dma': 'New York', 'formatted_address': '401 W 25th St (9th Ave), New York, NY 10001', 'locality': 'New York', 'postcode': '10001', 'region': 'NY'}, 'name': 'Citizens of Chelsea', 'related_places': {}, 'timezone': 'America/New_York'}, {'fsq_id': '619125bafb41d06a30c7d26b', 'categories': [{'id': 13102, 'name': 'Cantonese Restaurant', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/asian_', 'suffix': '.png'}}, {'id': 13106, 'name': 'Dim Sum Restaurant', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/dimsum_', 'suffix': '.png'}}], 'chains': [], 'distance': 247, 'geocodes': {'drop_off': {'latitude': 40.746984, 'longitude': -73.996589}, 'main': {'latitude': 40.747204, 'longitude': -73.996497}, 'roof': {'latitude': 40.747204, 'longitude': -73.996497}}, 'link': '/v3/places/619125bafb41d06a30c7d26b', 'location': {'address': '251 W 26th St', 'census_block': '360610095002003', 'country': 'US', 'cross_street': 'between 7th Ave and 8th Ave', 'dma': 'New York', 'formatted_address': '251 W 26th St (between 7th Ave and 8th Ave), New York, NY 10001', 'locality': 'New York', 'postcode': '10001', 'region': 'NY'}, 'name': 'Hey Yuet', 'related_places': {}, 'timezone': 'America/New_York'}, {'fsq_id': '540def3a498ee75cf369e5a6', 'categories': [{'id': 13002, 'name': 'Bakery', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/bakery_', 'suffix': '.png'}}, {'id': 13035, 'name': 'Coffee Shop', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/coffeeshop_', 'suffix': '.png'}}, {'id': 13065, 'name': 'Restaurant', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/default_', 'suffix': '.png'}}], 'chains': [], 'distance': 437, 'geocodes': {'main': {'latitude': 40.745543, 'longitude': -73.994073}, 'roof': {'latitude': 40.745543, 'longitude': -73.994073}}, 'link': '/v3/places/540def3a498ee75cf369e5a6', 'location': {'address': '275 7th Ave', 'address_extended': 'Frnt 3', 'census_block': '360610091005000', 'country': 'US', 'cross_street': 'btwn W 25th & W 26th St', 'dma': 'New York', 'formatted_address': '275 7th Ave (btwn W 25th & W 26th St), New York, NY 10001', 'locality': 'New York', 'postcode': '10001', 'region': 'NY'}, 'name': 'Seven Grams Caffe', 'related_places': {}, 'timezone': 'America/New_York'}]

In [ ]:
p1_lat_NY, p1_lon_NY, p2_lat_NY, p2_lon_NY, p3_lat_NY, p3_lon_NY = df['offices_latitude'][0], df['offices_longitude'][0], df['offices_latitude'][1], df['offices_longitude'][1], df['offices_latitude'][2], df['offices_longitude'][2]

In [ ]:
middle_lat_NY = median([p1_lat_NY, p2_lat_NY, p3_lat_NY])
middle_lon_NY = median([p1_lon_NY, p2_lon_NY, p3_lon_NY])

In [ ]:
testmap_NY = folium.Map(location=[middle_lat_NY, middle_lon_NY], zoom_start=13)

In [ ]:
folium.Circle(location=[p1_lat_NY, p1_lon_NY], popup='Point 1A', fill_color='#ff0000', radius=200, weight=2, color="#000000").add_to(testmap_NY)
folium.Circle(location=[p2_lat_NY, p2_lon_NY], popup='Point 1B', fill_color='#00ff00', radius=200, weight=2, color="#000000").add_to(testmap_NY)
folium.Circle(location=[p3_lat_NY, p3_lon_NY], popup='Point 1C', fill_color='#0000ff', radius=200, weight=2, color="#ffffff").add_to(testmap_NY)

In [ ]:
display(testmap_NY)

In [ ]:
for index, row in df.iterrows():
    
    all_together = {"location": [row["offices_latitude"], row["offices_longitude"]]}
            
    # 1. Check for the conditions of Festividad: to get the diferent Icon
    if row["num_vegan_rest"] != None:
        icon = Icon (
                icon = "laptop",
                prefix = "fa",
                color = "red",
                icon_color = "white")
        
    elif row["num_preschool"] != None:
        icon = Icon (
                icon = "moon-o",
                prefix = "fa",
                color = "white",
                icon_color = "black")
        
    elif row["num_starbucks"] != None:
        icon = Icon (
                icon = "cutlery",
                prefix = "fa",
                color = "green",
                icon_color = "white")
        
    elif row["num_airport"] != None:
        icon = Icon (
                icon = "cutlery",
                prefix = "fa",
                color = "green",
                icon_color = "white")
        
    elif row["num_clubs"] != None:
        icon = Icon (
                icon = "cutlery",
                prefix = "fa",
                color = "green",
                icon_color = "white")
    
    # 2. With the icon: I pass that to the Marker

    new_marker = Marker(**all_together, icon = icon)
    
    # 3. Add a Marker per row
    
    new_marker.add_to(testmap_NY)

testmap_NY

In [ ]:
for index, row in df.iterrows():
    
    all_together = {"location": [row["offices_latitude"], row["offices_longitude"]]}
            
    # 1. Check for the conditions of Festividad: to get the diferent Icon
    if row["num_vegan_rest"] != None:
        icon = Icon (
                icon = "laptop",
                prefix = "fa",
                color = "red",
                icon_color = "white")
      
    # 2. With the icon: I pass that to the Marker

    new_marker = Marker(**all_together, icon = icon)
    
    # 3. Add a Marker per row
    
    new_marker.add_to(testmap_NY)

testmap_NY